name: satip
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.12
  - cartopy
  - rasterio
  - rioxarray
  - fsspec
  - satpy
  - pip:
    - aiobotocore==2.12.1
    - aiohttp==3.9.3
    - aioitertools==0.11.0
    - aiosignal==1.3.1
    - alembic==1.13.1
    - annotated-types==0.6.0
    - blosc2==2.5.1
    - botocore==1.34.51
    - eumdac==2.2.1
    - freezegun==1.4.0
    - frozenlist==1.4.1
    - greenlet==3.0.3
    - iniconfig==2.0.0
    - jmespath==1.0.1
    - mako==1.3.2
    - multidict==6.0.5
    - ndindex==1.8
    - nowcasting-datamodel==1.5.30
    - ocf-blosc2==0.0.4
    - pluggy==1.4.0
    - psycopg2-binary==2.9.9
    - py-cpuinfo==9.0.0
    - pydantic==2.5.3
    - pydantic-core==2.14.6
    - pytest==8.0.2
    - s3fs==2024.2.0
    - sqlalchemy==2.0.28
    - structlog==24.1.0
    - typing-extensions==4.10.0
    - urllib3==1.26.18
    - wrapt==1.16.0
    - yarl==1.9.4
